import 'package:flutter/material.dart';

Map<String, List<Map<String, Color>>> allcolors = {
  'strong': [
    {'cardcolor': Color(0xFF16213E), 'fontcolor': Colors.white},
    {
      'cardcolor': Color(0xFF05299E),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF462255),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF8E8DBE),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF370926),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF0C6291),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF37423D),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF171614),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFFB1740F),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF32533D),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF8B6220),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF720E07),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF0C6291),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF456990),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF9A8873),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFF3A2618),
      'fontcolor': Colors.white,
    },
    {
      'cardcolor': Color(0xFFFB5012),
      'fontcolor': Colors.white,
    },
  ],
  'weak': [
    {
      'cardcolor': Color(0xFFFBFEF9),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFD8CFAF),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFF4ECDC4),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFFF6B6B),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFDDBDD5),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFF947BD3),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFA9E4EF),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFF96F550),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFCAC2B5),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFECDCC9),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFD0A98F),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFCFCFCF),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFFDB833),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFFFD07B),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFFA2AEBB),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFF98A6D4),
      'fontcolor': Colors.black,
    },
    {
      'cardcolor': Color(0xFF8CBA80),
      'fontcolor': Colors.black,
    },
  ],
};
Map<String, List<String>> langs = {
  "English": [
    "Sign in",
    "Welcome back! Let's input your login information",
    "Sign in with Google",
    "or Sign in with Email",
    "Email",
    "Password",
    "Forgot Password?",
    "New here?",
    "Register",
    "Welcome, Let's introduce yourself before we begin",
    "Optional Name Field",
    "First Name",
    "Last Name",
    "Already have an account?",
    "Forgot Password?",
    "Enter your Email, so we can send you a password reset link (check spam folder)",
    "Send reset link",
    "Almost There",
    "Verify your email address",
    "We've sent you an email verification. Please open it \n to verify your account (Check spam folder).",
    "If you haven't received a verification email, press the button below.",
    "SEND AGAIN",
    "My Notes",
    "Search",
    "No Data to fetch! Add Notes to see them here",
    "Setting",
    "Card Color",
    "Use default",
    "Generate randomly",
    "Choose Language",
    "Choose Theme",
    "Confirm before deleting",
    "Yes",
    "No",
    "Log out",
    "About",
    "My Notes 1.0.0+1  \nDeveloped by Alexander Alema & Mikyas Worku. \nContact @alexanderkalema to report bugs or for any enquiries.\nMore updates to follow soon!",
    "Delete",
    "Are you sure you want to delete this item?",
    "Are you sure you want to log out?",
    "An Error Occured",
    "Ok",
    "Cancel",
        'Cannot find a user with the entered credentials!',
    "Wrong credentials",
    "Authentication error",
    "Weak password",
    "Email already in use",
    "Failed to register",
    "Invalid Email",
    "We could not process your request. Please make sure that you are a registered user",
    "Password Reset ",
    "We have now sent you a password reset link. Please check your email for more information.",
    "Please wait a bit ",
  ],
  "Tigrigna": [
    "እቶ",
    "እንቋዕ ብደሓን መጻእኩም ሓበሬታኹም ኣእትዉ",
    "ብጉግል እቶ",
    "ብኢሜል እቶ",
    "ኢሜል",
    "ናይ ሚስጥር ቁልፊ ቃል",
    "ናይ ሚስጥር ቁልፊ ቃል ረሲኢኩም?",
    "ኣብዚ ሓድሽ ዲኩም?",
    "ምምዝጋብ",
    "እንቋዕ ብደሓን መጻእኩም ቅድሚ ምጅማርና ንፋለጥ",
    "ኣማራጺ ዓውደ ስም",
    "ቀዳማይ ስም",
    "ናይ መወዳእታ ስም",
    "ድሮ ጸብጻብ ኣሎካ?",
    "ፓስዎርድ ረሲኢኩም?",
    "ናይ password ሊንክ ክንሰደልኩም፣ ኢሜል ኣእትው (spam folder ረአይ)",
    "ሪሰት ሊንክ ስደድ",
    "ንእሸተይ ተሪፉኩም",
    "ኢመይልካ ኣረጋግጹ",
    "ናይ ኢመይል ምርግጋጽ ሰዲድናልኩም ኣለና።በጃኹም ክፈትዎ። ",
    "መረጋገጺ እንተዘይረኺብኩም ኣብ ታሕቲ ዘሎ ቁልፊ ጽቐጡ።",
    "ደጊምኩም ስደዱ።",
    "ናተይ መዝገብ",
    "ድለ",
    "ዳታ ኣይወሰኽኩምን! ኣብዚ ንምርኣይ መርጃ ወስኹ ",
    "ምምላእ",
    "ሕብሪ ካርድ",
    "ነባሪ ተጠቐም",
    "ብዘይ መደብ ፍጠር",
    "ቋንቋ ምረጽ",
    "ሕብሪ መተግበሪ",
    "ቅድሚ ምድምሳስካ ኣረጋግጽ?",
    "እወ",
    "አይኮንን",
    "ውጻእ",
    "ብዝዕባ",
    "ናተይ መዝገብ 1.0.0+1  \nብ Alexander Alema እና Mikyas Worku ተማዕቢሉ . \n ጸገም ንምሕባር አብ @alexanderkalema  ርኸቡኒ።\nተወሳኺ ሓድሽ ሓበሬታ ኣብ ቀረባ እዋን ክንውስብ ኢና።",
    "ምድምሳስ",
    "ነዚ ንብረት ክትድምስሶ ከም እትደሊ ርግጸኛ ዲኻ?",
    "ርግጸኛ ዲኩም ክትወጽኡ ከም እትደሊኡ?",
        "ጌጋ ኣጋጢሙ",
    "ሐራይ",
    "ንምምላስ",
    "ከምዚ መንነት ዘለዎ ተጠቃሚ ኽነርክብ ኣይክእልናን ኢና!",
    "ግጉይ ብቕዓታት",
    "ጌጋ ሓቅነት",
    "ድኹም ናይ ሚስጥር ቁልፊ ቃል",
    "ድሮ ኣብ ጥቕሚ ዝወዓላ ኢ-መይል",
    "ኪምዝገብ ኣይከኣለን",
    "ዘይግቡእ ኢ-መይል",
    "ሕቶኹም ከነሰላስል ኣይከኣልናን። በጃኹም ምዝጉብ ተጠቃሚ ምዃንኩም ኣረጋግጹ",
    "password ዳግማይ ምትካል",
    "ፓስዎርድ ሪሰት ሊንክ ሰዲድናልኩም ኣለና።ንዝያዳ ሓበሬታ ብኢመይልኩም ተወከሱ።",
    "በጃኹም ቁሩብ ተጸበዩ።",
  ],
  "Amharic": [
    "ይግቡ",
    "እንኳን በደህና መጡ! የመግቢያ መረጃዎን እናስገባ",
    "በጉግል ግቡ",
    "በኢሜል ግቡ",
    "ኢሜል",
    "የይለፍ ቃል",
    "የይለፍ ቃል ረስተዋል?",
    "እዚህ አዲስ ነዎት?",
    "ይመዝገቡ",
    "እንኳን ደህና መጡ ፣ ከመጀመራችን በፊት እራስዎን እናስተዋውቁ",
    "አማራጭ ስም መስክ",
    "የመጀመሪያ ስም",
    "የአባት ስም",
    "ቀድሞውኑ መለያ አሎት?",
    "የይለፍ ቃል ረስተዋል?",
    "የይለፍ ቃል ዳግም እንድልክልዎ፣ኢሜልዎን ያስገቡ (spam folder ይዪ)",
    "የሪሴት ሊንክ ላክ",
    "ትንሽ ይቀሮታል",
    "ኢሜልዎን ያረጋግጡ",
    "የኢሜል ማረጋገጫ ልከናል. እባክዎን ይክፈቱ  ",
    "ማረጋገጫ ካልተቀበሉ ከዚህ በታች ያለውን ቁልፍ ይጫኑ.",
    "እንደገና ይላኩ",
    "የኔ ማስታወሻ",
    "ፈልግ",
    "ምንም መረጃ አልጨመሩም! ማስታወሻዎችን ያክሉ እና እዚህ ይዩ",
    "ማስተካከያ",
    "ካርድ ቀለም",
    "ነባር ይጠቀሙ",
    "በዘፈቀደ ይፍጠሩ",
    "ቋንቋ ይምረጡ",
    "የመተግበሪያ ቀለም",
    "ከመሰረዝዎ በፊት ያረጋግጡ",
    "አዎ",
    "አይ",
    "ይውጡ",
    "ስለ",
    "የኔ ማስታወሻ 1.0.0+1  \n በ Alexander Alema እና Mikyas Worku ተስራ. \n በ @alexanderkalema ተጠቅማቹ ችግሮችን ሪፖርት አርጉ።\n ወደፊት ተጨማሪ ዝመናዎች ይመጣሉ ",
    "አጥፋ",
    "እርግጠኛ ነዎት ይህንን ዕቃ መሰረዝ ይፈልጋሉ?",
    "እርግጠኛ ነዎት መውጣት ይፈልጋሉ?",
    "ስህተት ተከስቷል",
    "እሺ",
    "ተመለስ",
    " የገቡ ማስረጃዎች ያሉት ተጠቃሚ ማግኘት አልተቻለም!",
    "የተሳሳቱ ማስረጃዎች",
    "የማረጋገጫ ስህተት",
    "ደካማ የይለፍ ቃል",
    "ቀድሞውኑ ጥቅም ላይ የዋለ ኢሜል",
    " መመዝገብ አልተሳካም",
    "ልክ ያልሆነ ኢሜል",
    "ጥያቄዎን ማስኬድ አልቻልንም. እባክዎ የተመዘገበ ተጠቃሚ መሆንዎን ያረጋግጡ",
    " የይለፍ ቃል ዳግም አስጀምር ",
    "የይለፍ ቃል ዳግም ለማስጀመር ሊንክ ልከናል. ለተጨማሪ መረጃ እባክዎን ኢሜልዎን ያረጋግጡ.",
    "እባክዎን ትንሽ ይጠብቁ",
  ],
  "Afaan Oromo": [
    "seeni",
    "Baga nagaan dhuftan! Mee odeeffannoo seensaa keessan haa galchinu",
    "Guugilii waliin galmaa'aa",
    "Imeelii tiin galmaa'aa",
    "Imeelii",
    "Jecha iccitii",
    "jecha icciitii dagattee jirtaa?",
    "Nama haaraadhaa ati?",
    "Galmaa'i",
    "Baga nagaan dhufte, Osoo hin jalqabin dura of haa beeksifnu",
    "Dirree Maqaa Filannoo",
    "Maqaa jalqabaa",
    "Maqaa akaakayyuu",
    "Duraan account qabdaa?",
    "Jecha Darbii Dagattee jirtaa",
    "Email keessan galchaa, kanaaf password reset link isiniif erguu dandeenya(galmee spam ilaali)",
    "Link reset ergaa",
    "Xumurree jirra",
    "Email keessan mirkaneessaa",
    "Mirkaneessa email isiniif ergineerra. Mee itti banadhaa .",
    "Yoo mirkaneessaa hin arganne ta'e, button armaan gadii dhiibaa",
    "AMMAS ERGAA",
    "Yaadannoo koo",
    "Barbaadi",
    "Daataa hin qabdu! yaadannoo dabaluudhaan asitti ilaaluu dandeessu",
    "Qundaa'ina",
    "Halluu Kaardii",
    "Durtii fayyadami",
    "Siistemiin haa maddisiisu",
    "Afaan filadhu",
    "Mata duree filadhu",
    "Haquu dura mirkaneessi?",
    "Eeyyee",
    "Lakki",
    "Ba'i",
    "Waa'ee",
    "Yaadannoo koo 1.0.0+1  kan Alexander Alema fi Mikyas Worku jedhamuun qophaa’e.Dogoggoraa fi dhimmoota gabaasuuf @alexanderkalema qunnamaa. \nOdeeffannoo dabalataa yeroo dhiyootti hordofuuf!",
    "Haquu",
    "Wanti kana haquu akka barbaaddu mirkaneeffatteettaa?",
    "Bahuu akka barbaaddu mirkaneeffatteettaa?",
    "Dogoggorri Mudate",
    "Tole",
    "Ni deebita",
    "Fayyadamaa mirkaneessa galfame qabu argachuu hin dandeenye!",
    "Mirkaneessitoota dogoggoraa",
    "Dogoggora mirkaneessuu",
    "Jecha icciitii dadhabaa",
    "Email duraanuu itti fayyadamaa jiru .",
    "Galmaa'uu dadhabe",
    "Imeelii Sirrii Hin Taane",
    "Gaaffii keessan adeemsisuu hin dandeenye. Fayyadamaa galmaa'e ta'uu kee mirkaneessi",
    "Jecha icciitii Reset",
    "Amma password reset link isiniif erginee jirra. Odeeffannoo dabalataaf email keessan ilaalaa.",
    "Mee xiqqoo eegaa",
  ],
};
